headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
publish = "C:\\Users\\haziq\\Averroes Data Science\\Company\\Projects\\2025\\HRMS\\Codes\\HRMS_v1\\dist\\HRMS_v1\\browser"
publishOrigin = "config"
commandOrigin = "config"
command = "ng build --configuration production"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https:; connect-src 'self' https://nextura-hrms-api.azurewebsites.net https://*.supabase.co; font-src 'self' https://fonts.gstatic.com; object-src 'none'; frame-src 'none';"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
from = "http://nextura-hrms.netlify.app/*"
to = "https://nextura-hrms.netlify.app/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]