import {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart,
  BarChart3,
  Bell,
  Bold,
  BookOpen,
  BookOpenText,
  Building,
  Building2,
  Calendar,
  CalendarPlus,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CirclePlus,
  CircleSmall,
  CircleX,
  CircleUser,
  Clipboard,
  Clock,
  Code,
  CodeXml,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  FileX,
  Flag,
  FileSearch,
  FileText,
  Folder,
  FolderCode,
  FolderOpen,
  FolderPlus,
  Globe,
  Hash,
  Heart,
  House,
  Inbox,
  Info,
  Italic,
  Key,
  Landmark,
  Layers,
  Layers2,
  LayoutDashboard,
  Lightbulb,
  LightbulbOff,
  Link,
  List,
  ListFilter,
  ListFilterPlus,
  LoaderCircle,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  type LucideIconData,
  Mail,
  MailOpen,
  Megaphone,
  Minus,
  Monitor,
  Moon,
  MoveRight,
  Palette,
  PanelLeft,
  Paperclip,
  Pencil,
  Phone,
  Pin,
  Plus,
  Popcorn,
  Puzzle,
  ReceiptText,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  SquareLibrary,
  Star,
  Sun,
  SunMoon,
  Tablet,
  Tag,
  Terminal,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignStart,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Underline,
  Unlink,
  Briefcase,
  User,
  UserCircle,
  UserPlus,
  Users,
  UserX,
  Wallet,
  X,
  Zap,
  UserMinus,
  FileSpreadsheet,
  FileChartPie,
  FileChartColumn,
  FileChartLine,
  FileChartColumnIncreasing,
  FilePlus,
  KeyRound,
  CalendarCheck,
  CalendarX,
  ShieldCheck,
  Timer,
  MapPin,
  MessageSquare,
  MessageSquarePlus,
  Upload,
  HardDrive,
  PieChart,
  Filter,
  ArrowUpDown,
  ArrowDown,
  Image,
  FileType2,
  FileArchive,
  Package,
  StickyNote,
  TicketCheck,
  TextAlignJustify,
  Printer,
  Home,
  Play,
} from 'lucide-angular';

const DarkMode: LucideIconData = [
  ['path', { d: 'M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0' }],
  ['path', { d: 'M12 3l0 18' }],
  ['path', { d: 'M12 9l4.65 -4.65' }],
  ['path', { d: 'M12 14.3l7.37 -7.37' }],
  ['path', { d: 'M12 19.6l8.85 -8.85' }],
];

export const ZARD_ICONS = {
  house: House,
  settings: Settings,
  user: User,
  'user-minus': UserMinus,
  search: Search,
  bell: Bell,
  mail: Mail,
  'mail-open': MailOpen,
  calendar: Calendar,
  'log-in': LogIn,
  'log-out': LogOut,
  'panel-left': PanelLeft,
  bold: Bold,
  inbox: Inbox,
  italic: Italic,
  underline: Underline,
  'text-align-center': TextAlignCenter,
  'text-align-end': TextAlignEnd,
  'text-align-start': TextAlignStart,
  check: Check,
  x: X,
  info: Info,
  'triangle-alert': TriangleAlert,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-plus': CirclePlus,
  'circle-x': CircleX,
  'circle-dollar-sign': CircleDollarSign,
  'circle-small': CircleSmall,
  ban: Ban,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'move-right': MoveRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  file: File,
  globe: Globe,
  'file-chart-column': FileChartColumn,
  'file-chart-pie': FileChartPie,
  'file-chart-bar-increasing': FileChartColumnIncreasing,
  'file-chart-line': FileChartLine,
  'file-search': FileSearch,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'layout-dashboard': LayoutDashboard,
  'loader-circle': LoaderCircle,
  save: Save,
  copy: Copy,
  eye: Eye,
  'eye-off': EyeOff,
  ellipsis: Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  terminal: Terminal,
  clipboard: Clipboard,
  moon: Moon,
  sun: Sun,
  lightbulb: Lightbulb,
  'lightbulb-off': LightbulbOff,
  palette: Palette,
  sparkles: Sparkles,
  hash: Hash,
  heart: Heart,
  star: Star,
  zap: Zap,
  popcorn: Popcorn,
  shield: Shield,
  puzzle: Puzzle,
  layers: Layers,
  'layers-2': Layers2,
  'square-library': SquareLibrary,
  code: Code,
  'code-xml': CodeXml,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  users: Users,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  'badge-check': BadgeCheck,
  'folder-code': FolderCode,
  plus: Plus,
  minus: Minus,
  'arrow-left': ArrowLeft,
  archive: Archive,
  clock: Clock,
  'calendar-plus': CalendarPlus,
  'list-filter-plus': ListFilterPlus,
  trash: Trash2,
  tag: Tag,
  'sun-moon': SunMoon,
  'dark-mode': DarkMode,
  square: Square,
  'dollar-sign': DollarSign,
  'user-plus': UserPlus,
  'circle-user': CircleUser,
  'credit-card': CreditCard,
  activity: Activity,
  paperclip: Paperclip,
  pencil: Pencil,
  'ticket-check': TicketCheck,
  download: Download,
  megaphone: Megaphone,
  'refresh-cw': RefreshCw,
  flag: Flag,
  'check-square': SquareCheck,
  'plus-circle': Plus,
  send: Send,
  'bar-chart': BarChart,
  'check-circle': CheckCircle,
  'receipt-text': ReceiptText,
  'alert-circle': AlertCircle,
  building: Building,
  'building-2': Building2,
  list: List,
  'list-filter': ListFilter,
  'trending-up': TrendingUp,
  wallet: Wallet,
  'bar-chart-3': BarChart3,
  'user-circle': UserCircle,
  key: Key,
  lock: Lock,
  phone: Phone,
  briefcase: Briefcase,
  'loader-2': Loader2,
  banknote: Banknote,
  landmark: Landmark,
  'file-x': FileX,
  'user-x': UserX,
  'link': Link,
  'unlink': Unlink,
  'key-round': KeyRound,
  'calendar-check': CalendarCheck,
  'calendar-x': CalendarX,
  'shield-check': ShieldCheck,
  'timer': Timer,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  'message-square-plus': MessageSquarePlus,
  'upload': Upload,
  'hard-drive': HardDrive,
  pin: Pin,
  'pie-chart': PieChart,
  'filter': Filter,
  'arrow-up-down': ArrowUpDown,
  'arrow-down': ArrowDown,
  'image': Image,
  'file-type': FileType2,
  'file-archive': FileArchive,
  'trash-2': Trash2,
  'text-align-justify': TextAlignJustify,
  'file-plus': FilePlus,
  'package': Package,
  'sticky-note': StickyNote,
  'printer': Printer,
  'home': Home,
  'play': Play
} as const satisfies Record<string, LucideIconData>;

export declare type ZardIcon = keyof typeof ZARD_ICONS | LucideIconData;
